version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/install:
            node-version: "16.13.1"
      - run: node -v
      - node/with-cache:
          steps:
            - run: npm install
      - run: npx playwright --version
      - run: npm run test -- --project="chromium" --workers=4

      - store_artifacts:
          destination: playwright-report
          path: ./playwright-report
      - store_artifacts:
          destination: traces
          path: ./test-results
workflows:
  version: 2
  workflow:
    jobs:
      - build
