version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npx playwright --version
      - run: npm run test -- --project="chromium" --workers=4

      - store_artifacts:
          path: ./playwright-report/index.html
      - store_artifacts:
          path: ./test-results/*.zip
workflows:
  version: 2
  workflow:
    jobs:
      - build
