# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-actions ]
  pull_request:
    branches: [ gh-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_run_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: npx playwright test verge.spec.js --config=playwright.config.js --shard=1/3
  test_run_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: npx playwright test verge.spec.js --config=playwright.config.js --shard=2/3
  test_run_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: npx playwright test verge.spec.js --config=playwright.config.js --shard=3/3

